%%{ init: { 'theme': 'base', 'themeVariables': { 'background': '#243A5E', 'primaryColor': '#50E6FF', 'primaryBorderColor': '#243A5E', 'tertiaryBorderColor': '#50E6FF', 'tertiaryColor': '#243A5E', 'fontFamily': 'Segoe UI', 'lineColor': '#FFFFFF', 'primaryTextColor': '#243A5E', 'tertiaryTextColor': '#FFFFFF' } }}%%
flowchart LR
    subgraph pk-helmets[Partition Key: Helmets]
        direction TB
        cat-helmets([Category: Helmets])
    end
    subgraph pk-tents[Partition Key: Tents]
        direction BT
        cat-tents([Category: Tents])
        prd-cirroa[Product: Cirroa Tent]
        prd-kuloar[Product: Kuloar Tent]
        prd-mammatin[Product: Mammatin Tent]
        prd-nimbolo[Product: Nimbolo Tent]
    end