### YamlMime:ModuleUnit
uid: learn.dpu.windows-11-zero-touch.deployment-constraints
title: Identify deployment constraints that require zero‑touch provisioning
metadata:
  title: Identify Deployment Constraints That Require Zero‑touch Provisioning
  description: This content is part of the "Deliver zero-touch Windows 11 Pro deployments" module.
  ms.date: 06/04/2026
  author: melissawinters
  ms.author: v-mwinters
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/2-deployment-constraints.md)]
