var virtualNetworkName = 'ToyTruck-vnet'
var virtualMachineName = 'ToyTruckServer'
var networkInterfaceName = 'YOUR-NETWORK-INTERFACE-NAME'
var publicIPAddressName = 'ToyTruckServer-ip'
var networkSecurityGroupName = 'ToyTruckServer-nsg'
